import React, { useState, useEffect } from "react";



export default function Header() {
  // Define date
  const [currentDate, setDateState] = useState(new Date());
  const [currentWeather, setWeatherState] = useState({
    location: {
      name: "Brighton",
      region: "East Sussex",
      country: "United Kingdom",
      lat: 50.84,
      lon: -0.13,
      tz_id: "Europe/London",
      localtime_epoch: 1639045418,
      localtime: "2021-12-09 10:23",
    },
    current: {
      last_updated_epoch: 1639044900,
      last_updated: "2021-12-09 10:15",
      temp_c: 4,
      temp_f: 39.2,
      is_day: 1,
      condition: {
        text: "Sunny",
        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
        code: 1000,
      },
      wind_mph: 4.3,
      wind_kph: 6.8,
      wind_degree: 210,
      wind_dir: "SSW",
      pressure_mb: 1003,
      pressure_in: 29.62,
      precip_mm: 0,
      precip_in: 0,
      humidity: 81,
      cloud: 0,
      feelslike_c: -0.6,
      feelslike_f: 30.8,
      vis_km: 10,
      vis_miles: 6,
      uv: 3,
      gust_mph: 20.8,
      gust_kph: 33.5,
    },
    forecast: {
      forecastday: [
        {
          date: "2021-12-09",
          date_epoch: 1639008000,
          day: {
            maxtemp_c: 9.5,
            maxtemp_f: 49.1,
            mintemp_c: 5.9,
            mintemp_f: 42.6,
            avgtemp_c: 8,
            avgtemp_f: 46.4,
            maxwind_mph: 25.5,
            maxwind_kph: 41,
            totalprecip_mm: 5,
            totalprecip_in: 0.2,
            avgvis_km: 9.2,
            avgvis_miles: 5,
            avghumidity: 77,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 93,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            uv: 1,
          },
          astro: {
            sunrise: "07:51 AM",
            sunset: "03:55 PM",
            moonrise: "12:26 PM",
            moonset: "09:59 PM",
            moon_phase: "First Quarter",
            moon_illumination: "41",
          },
          hour: [
            {
              time_epoch: 1639008000,
              time: "2021-12-09 00:00",
              temp_c: 6.8,
              temp_f: 44.2,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 23.5,
              wind_kph: 37.8,
              wind_degree: 272,
              wind_dir: "W",
              pressure_mb: 1001,
              pressure_in: 29.55,
              precip_mm: 0,
              precip_in: 0,
              humidity: 79,
              cloud: 92,
              feelslike_c: 1.8,
              feelslike_f: 35.2,
              windchill_c: 1.8,
              windchill_f: 35.2,
              heatindex_c: 6.8,
              heatindex_f: 44.2,
              dewpoint_c: 3.5,
              dewpoint_f: 38.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 32.2,
              gust_kph: 51.8,
              uv: 1,
            },
            {
              time_epoch: 1639011600,
              time: "2021-12-09 01:00",
              temp_c: 6.9,
              temp_f: 44.4,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 22.4,
              wind_kph: 36,
              wind_degree: 276,
              wind_dir: "W",
              pressure_mb: 1000,
              pressure_in: 29.54,
              precip_mm: 0,
              precip_in: 0,
              humidity: 76,
              cloud: 60,
              feelslike_c: 2.1,
              feelslike_f: 35.8,
              windchill_c: 2.1,
              windchill_f: 35.8,
              heatindex_c: 6.9,
              heatindex_f: 44.4,
              dewpoint_c: 2.9,
              dewpoint_f: 37.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 31.3,
              gust_kph: 50.4,
              uv: 1,
            },
            {
              time_epoch: 1639015200,
              time: "2021-12-09 02:00",
              temp_c: 7.2,
              temp_f: 45,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 24.4,
              wind_kph: 39.2,
              wind_degree: 276,
              wind_dir: "W",
              pressure_mb: 1001,
              pressure_in: 29.56,
              precip_mm: 0,
              precip_in: 0,
              humidity: 71,
              cloud: 94,
              feelslike_c: 2.3,
              feelslike_f: 36.1,
              windchill_c: 2.3,
              windchill_f: 36.1,
              heatindex_c: 7.2,
              heatindex_f: 45,
              dewpoint_c: 2.4,
              dewpoint_f: 36.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 34,
              gust_kph: 54.7,
              uv: 1,
            },
            {
              time_epoch: 1639018800,
              time: "2021-12-09 03:00",
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 24.8,
              wind_kph: 40,
              wind_degree: 277,
              wind_dir: "W",
              pressure_mb: 1001,
              pressure_in: 29.56,
              precip_mm: 0,
              precip_in: 0,
              humidity: 72,
              cloud: 65,
              feelslike_c: 2.6,
              feelslike_f: 36.7,
              windchill_c: 2.6,
              windchill_f: 36.7,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: 2.9,
              dewpoint_f: 37.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 34,
              gust_kph: 54.7,
              uv: 1,
            },
            {
              time_epoch: 1639022400,
              time: "2021-12-09 04:00",
              temp_c: 7.1,
              temp_f: 44.8,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 23.5,
              wind_kph: 37.8,
              wind_degree: 279,
              wind_dir: "W",
              pressure_mb: 1002,
              pressure_in: 29.58,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 44,
              feelslike_c: 2.2,
              feelslike_f: 36,
              windchill_c: 2.2,
              windchill_f: 36,
              heatindex_c: 7.1,
              heatindex_f: 44.8,
              dewpoint_c: 2.8,
              dewpoint_f: 37,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 32.4,
              gust_kph: 52.2,
              uv: 1,
            },
            {
              time_epoch: 1639026000,
              time: "2021-12-09 05:00",
              temp_c: 6.6,
              temp_f: 43.9,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 21.7,
              wind_kph: 34.9,
              wind_degree: 284,
              wind_dir: "WNW",
              pressure_mb: 1002,
              pressure_in: 29.6,
              precip_mm: 0,
              precip_in: 0,
              humidity: 75,
              cloud: 84,
              feelslike_c: 1.8,
              feelslike_f: 35.2,
              windchill_c: 1.8,
              windchill_f: 35.2,
              heatindex_c: 6.6,
              heatindex_f: 43.9,
              dewpoint_c: 2.6,
              dewpoint_f: 36.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 30.2,
              gust_kph: 48.6,
              uv: 1,
            },
            {
              time_epoch: 1639029600,
              time: "2021-12-09 06:00",
              temp_c: 6.3,
              temp_f: 43.3,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 19.5,
              wind_kph: 31.3,
              wind_degree: 288,
              wind_dir: "WNW",
              pressure_mb: 1003,
              pressure_in: 29.61,
              precip_mm: 0,
              precip_in: 0,
              humidity: 76,
              cloud: 32,
              feelslike_c: 1.6,
              feelslike_f: 34.9,
              windchill_c: 1.6,
              windchill_f: 34.9,
              heatindex_c: 6.3,
              heatindex_f: 43.3,
              dewpoint_c: 2.4,
              dewpoint_f: 36.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 27.1,
              gust_kph: 43.6,
              uv: 1,
            },
            {
              time_epoch: 1639033200,
              time: "2021-12-09 07:00",
              temp_c: 6.1,
              temp_f: 43,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 17.7,
              wind_kph: 28.4,
              wind_degree: 281,
              wind_dir: "WNW",
              pressure_mb: 1003,
              pressure_in: 29.62,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 42,
              feelslike_c: 1.6,
              feelslike_f: 34.9,
              windchill_c: 1.6,
              windchill_f: 34.9,
              heatindex_c: 6.1,
              heatindex_f: 43,
              dewpoint_c: 2.4,
              dewpoint_f: 36.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 25.1,
              gust_kph: 40.3,
              uv: 1,
            },
            {
              time_epoch: 1639036800,
              time: "2021-12-09 08:00",
              temp_c: 5.9,
              temp_f: 42.6,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 17.4,
              wind_kph: 28.1,
              wind_degree: 275,
              wind_dir: "W",
              pressure_mb: 1004,
              pressure_in: 29.63,
              precip_mm: 0,
              precip_in: 0,
              humidity: 78,
              cloud: 32,
              feelslike_c: 1.4,
              feelslike_f: 34.5,
              windchill_c: 1.4,
              windchill_f: 34.5,
              heatindex_c: 5.9,
              heatindex_f: 42.6,
              dewpoint_c: 2.3,
              dewpoint_f: 36.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 25.5,
              gust_kph: 41,
              uv: 3,
            },
            {
              time_epoch: 1639040400,
              time: "2021-12-09 09:00",
              temp_c: 6.2,
              temp_f: 43.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 14.8,
              wind_kph: 23.8,
              wind_degree: 277,
              wind_dir: "W",
              pressure_mb: 1004,
              pressure_in: 29.65,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 24,
              feelslike_c: 2.2,
              feelslike_f: 36,
              windchill_c: 2.2,
              windchill_f: 36,
              heatindex_c: 6.2,
              heatindex_f: 43.2,
              dewpoint_c: 2.5,
              dewpoint_f: 36.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.8,
              gust_kph: 33.5,
              uv: 3,
            },
            {
              time_epoch: 1639044000,
              time: "2021-12-09 10:00",
              temp_c: 6.6,
              temp_f: 43.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 14.1,
              wind_kph: 22.7,
              wind_degree: 273,
              wind_dir: "W",
              pressure_mb: 1004,
              pressure_in: 29.65,
              precip_mm: 0,
              precip_in: 0,
              humidity: 75,
              cloud: 20,
              feelslike_c: 2.8,
              feelslike_f: 37,
              windchill_c: 2.8,
              windchill_f: 37,
              heatindex_c: 6.6,
              heatindex_f: 43.9,
              dewpoint_c: 2.5,
              dewpoint_f: 36.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.5,
              gust_kph: 31.3,
              uv: 3,
            },
            {
              time_epoch: 1639047600,
              time: "2021-12-09 11:00",
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 14.3,
              wind_kph: 23,
              wind_degree: 269,
              wind_dir: "W",
              pressure_mb: 1004,
              pressure_in: 29.65,
              precip_mm: 0,
              precip_in: 0,
              humidity: 72,
              cloud: 46,
              feelslike_c: 3.9,
              feelslike_f: 39,
              windchill_c: 3.9,
              windchill_f: 39,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: 2.8,
              dewpoint_f: 37,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.7,
              gust_kph: 28.4,
              uv: 3,
            },
            {
              time_epoch: 1639051200,
              time: "2021-12-09 12:00",
              temp_c: 8,
              temp_f: 46.4,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 15.4,
              wind_kph: 24.8,
              wind_degree: 266,
              wind_dir: "W",
              pressure_mb: 1004,
              pressure_in: 29.64,
              precip_mm: 0,
              precip_in: 0,
              humidity: 69,
              cloud: 95,
              feelslike_c: 4.4,
              feelslike_f: 39.9,
              windchill_c: 4.4,
              windchill_f: 39.9,
              heatindex_c: 8,
              heatindex_f: 46.4,
              dewpoint_c: 2.7,
              dewpoint_f: 36.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.2,
              gust_kph: 31,
              uv: 2,
            },
            {
              time_epoch: 1639054800,
              time: "2021-12-09 13:00",
              temp_c: 9.4,
              temp_f: 48.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 15.2,
              wind_kph: 24.5,
              wind_degree: 262,
              wind_dir: "W",
              pressure_mb: 1003,
              pressure_in: 29.63,
              precip_mm: 0,
              precip_in: 0,
              humidity: 67,
              cloud: 10,
              feelslike_c: 6.2,
              feelslike_f: 43.2,
              windchill_c: 6.2,
              windchill_f: 43.2,
              heatindex_c: 9.4,
              heatindex_f: 48.9,
              dewpoint_c: 3.5,
              dewpoint_f: 38.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.4,
              gust_kph: 28.1,
              uv: 3,
            },
            {
              time_epoch: 1639058400,
              time: "2021-12-09 14:00",
              temp_c: 8.9,
              temp_f: 48,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 14.1,
              wind_kph: 22.7,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1002,
              pressure_in: 29.6,
              precip_mm: 0,
              precip_in: 0,
              humidity: 66,
              cloud: 100,
              feelslike_c: 5.7,
              feelslike_f: 42.3,
              windchill_c: 5.7,
              windchill_f: 42.3,
              heatindex_c: 8.9,
              heatindex_f: 48,
              dewpoint_c: 2.8,
              dewpoint_f: 37,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.9,
              gust_kph: 28.8,
              uv: 2,
            },
            {
              time_epoch: 1639062000,
              time: "2021-12-09 15:00",
              temp_c: 9.5,
              temp_f: 49.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 14.3,
              wind_kph: 23,
              wind_degree: 245,
              wind_dir: "WSW",
              pressure_mb: 1002,
              pressure_in: 29.59,
              precip_mm: 0,
              precip_in: 0,
              humidity: 66,
              cloud: 17,
              feelslike_c: 6.5,
              feelslike_f: 43.7,
              windchill_c: 6.5,
              windchill_f: 43.7,
              heatindex_c: 9.5,
              heatindex_f: 49.1,
              dewpoint_c: 3.5,
              dewpoint_f: 38.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.4,
              gust_kph: 28.1,
              uv: 3,
            },
            {
              time_epoch: 1639065600,
              time: "2021-12-09 16:00",
              temp_c: 9,
              temp_f: 48.2,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 14.1,
              wind_kph: 22.7,
              wind_degree: 229,
              wind_dir: "SW",
              pressure_mb: 1001,
              pressure_in: 29.57,
              precip_mm: 0,
              precip_in: 0,
              humidity: 68,
              cloud: 38,
              feelslike_c: 5.9,
              feelslike_f: 42.6,
              windchill_c: 5.9,
              windchill_f: 42.6,
              heatindex_c: 9,
              heatindex_f: 48.2,
              dewpoint_c: 3.3,
              dewpoint_f: 37.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.9,
              gust_kph: 32,
              uv: 1,
            },
            {
              time_epoch: 1639069200,
              time: "2021-12-09 17:00",
              temp_c: 9,
              temp_f: 48.2,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 14.5,
              wind_kph: 23.4,
              wind_degree: 215,
              wind_dir: "SW",
              pressure_mb: 1000,
              pressure_in: 29.54,
              precip_mm: 0,
              precip_in: 0,
              humidity: 70,
              cloud: 93,
              feelslike_c: 5.8,
              feelslike_f: 42.4,
              windchill_c: 5.8,
              windchill_f: 42.4,
              heatindex_c: 9,
              heatindex_f: 48.2,
              dewpoint_c: 3.9,
              dewpoint_f: 39,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 21.5,
              gust_kph: 34.6,
              uv: 1,
            },
            {
              time_epoch: 1639072800,
              time: "2021-12-09 18:00",
              temp_c: 9,
              temp_f: 48.2,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 17.4,
              wind_kph: 28.1,
              wind_degree: 202,
              wind_dir: "SSW",
              pressure_mb: 999,
              pressure_in: 29.51,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 83,
              cloud: 100,
              feelslike_c: 5.4,
              feelslike_f: 41.7,
              windchill_c: 5.4,
              windchill_f: 41.7,
              heatindex_c: 9,
              heatindex_f: 48.2,
              dewpoint_c: 6.2,
              dewpoint_f: 43.2,
              will_it_rain: 1,
              chance_of_rain: 72,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 24.2,
              gust_kph: 38.9,
              uv: 1,
            },
            {
              time_epoch: 1639076400,
              time: "2021-12-09 19:00",
              temp_c: 9.7,
              temp_f: 49.5,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 22.1,
              wind_kph: 35.6,
              wind_degree: 192,
              wind_dir: "SSW",
              pressure_mb: 998,
              pressure_in: 29.47,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 88,
              cloud: 100,
              feelslike_c: 5.8,
              feelslike_f: 42.4,
              windchill_c: 5.8,
              windchill_f: 42.4,
              heatindex_c: 9.7,
              heatindex_f: 49.5,
              dewpoint_c: 7.7,
              dewpoint_f: 45.9,
              will_it_rain: 1,
              chance_of_rain: 92,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 28,
              gust_kph: 45,
              uv: 1,
            },
            {
              time_epoch: 1639080000,
              time: "2021-12-09 20:00",
              temp_c: 9.2,
              temp_f: 48.6,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 24.4,
              wind_kph: 39.2,
              wind_degree: 187,
              wind_dir: "S",
              pressure_mb: 996,
              pressure_in: 29.41,
              precip_mm: 0,
              precip_in: 0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 5,
              feelslike_f: 41,
              windchill_c: 5,
              windchill_f: 41,
              heatindex_c: 9.2,
              heatindex_f: 48.6,
              dewpoint_c: 7.6,
              dewpoint_f: 45.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 33.1,
              gust_kph: 53.3,
              uv: 1,
            },
            {
              time_epoch: 1639083600,
              time: "2021-12-09 21:00",
              temp_c: 9.1,
              temp_f: 48.4,
              is_day: 0,
              condition: {
                text: "Moderate rain",
                icon: "//cdn.weatherapi.com/weather/64x64/night/302.png",
                code: 1189,
              },
              wind_mph: 25.5,
              wind_kph: 41,
              wind_degree: 181,
              wind_dir: "S",
              pressure_mb: 994,
              pressure_in: 29.36,
              precip_mm: 3.3,
              precip_in: 0.13,
              humidity: 94,
              cloud: 100,
              feelslike_c: 4.7,
              feelslike_f: 40.5,
              windchill_c: 4.7,
              windchill_f: 40.5,
              heatindex_c: 9.1,
              heatindex_f: 48.4,
              dewpoint_c: 8.2,
              dewpoint_f: 46.8,
              will_it_rain: 1,
              chance_of_rain: 93,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 7,
              vis_miles: 4,
              gust_mph: 34.2,
              gust_kph: 55.1,
              uv: 1,
            },
            {
              time_epoch: 1639087200,
              time: "2021-12-09 22:00",
              temp_c: 9.7,
              temp_f: 49.5,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 24.4,
              wind_kph: 39.2,
              wind_degree: 191,
              wind_dir: "SSW",
              pressure_mb: 992,
              pressure_in: 29.3,
              precip_mm: 0,
              precip_in: 0,
              humidity: 96,
              cloud: 100,
              feelslike_c: 5.6,
              feelslike_f: 42.1,
              windchill_c: 5.6,
              windchill_f: 42.1,
              heatindex_c: 9.7,
              heatindex_f: 49.5,
              dewpoint_c: 9.1,
              dewpoint_f: 48.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 33.1,
              gust_kph: 53.3,
              uv: 1,
            },
            {
              time_epoch: 1639090800,
              time: "2021-12-09 23:00",
              temp_c: 10.9,
              temp_f: 51.6,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 18.6,
              wind_kph: 29.9,
              wind_degree: 264,
              wind_dir: "W",
              pressure_mb: 991,
              pressure_in: 29.26,
              precip_mm: 1,
              precip_in: 0.04,
              humidity: 90,
              cloud: 100,
              feelslike_c: 7.8,
              feelslike_f: 46,
              windchill_c: 7.8,
              windchill_f: 46,
              heatindex_c: 10.9,
              heatindex_f: 51.6,
              dewpoint_c: 9.3,
              dewpoint_f: 48.7,
              will_it_rain: 1,
              chance_of_rain: 92,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 26.2,
              gust_kph: 42.1,
              uv: 1,
            },
          ],
        },
        {
          date: "2021-12-10",
          date_epoch: 1639094400,
          day: {
            maxtemp_c: 8.4,
            maxtemp_f: 47.1,
            mintemp_c: 5.4,
            mintemp_f: 41.7,
            avgtemp_c: 6.9,
            avgtemp_f: 44.4,
            maxwind_mph: 31.5,
            maxwind_kph: 50.8,
            totalprecip_mm: 5.9,
            totalprecip_in: 0.23,
            avgvis_km: 9.3,
            avgvis_miles: 5,
            avghumidity: 77,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 92,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            uv: 1,
          },
          astro: {
            sunrise: "07:52 AM",
            sunset: "03:55 PM",
            moonrise: "12:45 PM",
            moonset: "11:17 PM",
            moon_phase: "First Quarter",
            moon_illumination: "48",
          },
          hour: [
            {
              time_epoch: 1639094400,
              time: "2021-12-10 00:00",
              temp_c: 8.1,
              temp_f: 46.6,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 26.4,
              wind_kph: 42.5,
              wind_degree: 318,
              wind_dir: "NW",
              pressure_mb: 992,
              pressure_in: 29.28,
              precip_mm: 1.7,
              precip_in: 0.07,
              humidity: 87,
              cloud: 100,
              feelslike_c: 3.3,
              feelslike_f: 37.9,
              windchill_c: 3.3,
              windchill_f: 37.9,
              heatindex_c: 8.1,
              heatindex_f: 46.6,
              dewpoint_c: 6,
              dewpoint_f: 42.8,
              will_it_rain: 1,
              chance_of_rain: 92,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 37.1,
              gust_kph: 59.8,
              uv: 1,
            },
            {
              time_epoch: 1639098000,
              time: "2021-12-10 01:00",
              temp_c: 8.3,
              temp_f: 46.9,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 27.1,
              wind_kph: 43.6,
              wind_degree: 306,
              wind_dir: "NW",
              pressure_mb: 992,
              pressure_in: 29.28,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 84,
              cloud: 100,
              feelslike_c: 3.5,
              feelslike_f: 38.3,
              windchill_c: 3.5,
              windchill_f: 38.3,
              heatindex_c: 8.3,
              heatindex_f: 46.9,
              dewpoint_c: 5.8,
              dewpoint_f: 42.4,
              will_it_rain: 0,
              chance_of_rain: 70,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 37.1,
              gust_kph: 59.8,
              uv: 1,
            },
            {
              time_epoch: 1639101600,
              time: "2021-12-10 02:00",
              temp_c: 7.4,
              temp_f: 45.3,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 25.3,
              wind_kph: 40.7,
              wind_degree: 302,
              wind_dir: "WNW",
              pressure_mb: 992,
              pressure_in: 29.3,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 86,
              cloud: 100,
              feelslike_c: 2.5,
              feelslike_f: 36.5,
              windchill_c: 2.5,
              windchill_f: 36.5,
              heatindex_c: 7.4,
              heatindex_f: 45.3,
              dewpoint_c: 5.3,
              dewpoint_f: 41.5,
              will_it_rain: 1,
              chance_of_rain: 74,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 34.2,
              gust_kph: 55.1,
              uv: 1,
            },
            {
              time_epoch: 1639105200,
              time: "2021-12-10 03:00",
              temp_c: 6.9,
              temp_f: 44.4,
              is_day: 0,
              condition: {
                text: "Light rain",
                icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
                code: 1183,
              },
              wind_mph: 31.5,
              wind_kph: 50.8,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 993,
              pressure_in: 29.33,
              precip_mm: 1.3,
              precip_in: 0.05,
              humidity: 89,
              cloud: 100,
              feelslike_c: 1.2,
              feelslike_f: 34.2,
              windchill_c: 1.2,
              windchill_f: 34.2,
              heatindex_c: 6.9,
              heatindex_f: 44.4,
              dewpoint_c: 5.2,
              dewpoint_f: 41.4,
              will_it_rain: 1,
              chance_of_rain: 91,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 41.4,
              gust_kph: 66.6,
              uv: 1,
            },
            {
              time_epoch: 1639108800,
              time: "2021-12-10 04:00",
              temp_c: 6.6,
              temp_f: 43.9,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 26.8,
              wind_kph: 43.2,
              wind_degree: 307,
              wind_dir: "NW",
              pressure_mb: 994,
              pressure_in: 29.36,
              precip_mm: 0.4,
              precip_in: 0.02,
              humidity: 85,
              cloud: 100,
              feelslike_c: 1.2,
              feelslike_f: 34.2,
              windchill_c: 1.2,
              windchill_f: 34.2,
              heatindex_c: 6.6,
              heatindex_f: 43.9,
              dewpoint_c: 4.2,
              dewpoint_f: 39.6,
              will_it_rain: 0,
              chance_of_rain: 67,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 35.8,
              gust_kph: 57.6,
              uv: 1,
            },
            {
              time_epoch: 1639112400,
              time: "2021-12-10 05:00",
              temp_c: 6.7,
              temp_f: 44.1,
              is_day: 0,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
                code: 1240,
              },
              wind_mph: 28.4,
              wind_kph: 45.7,
              wind_degree: 309,
              wind_dir: "NW",
              pressure_mb: 995,
              pressure_in: 29.38,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 77,
              cloud: 78,
              feelslike_c: 1.2,
              feelslike_f: 34.2,
              windchill_c: 1.2,
              windchill_f: 34.2,
              heatindex_c: 6.7,
              heatindex_f: 44.1,
              dewpoint_c: 3,
              dewpoint_f: 37.4,
              will_it_rain: 1,
              chance_of_rain: 73,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 38,
              gust_kph: 61.2,
              uv: 1,
            },
            {
              time_epoch: 1639116000,
              time: "2021-12-10 06:00",
              temp_c: 6,
              temp_f: 42.8,
              is_day: 0,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 26.4,
              wind_kph: 42.5,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 996,
              pressure_in: 29.41,
              precip_mm: 1.5,
              precip_in: 0.06,
              humidity: 78,
              cloud: 73,
              feelslike_c: 0.5,
              feelslike_f: 32.9,
              windchill_c: 0.5,
              windchill_f: 32.9,
              heatindex_c: 6,
              heatindex_f: 42.8,
              dewpoint_c: 2.4,
              dewpoint_f: 36.3,
              will_it_rain: 0,
              chance_of_rain: 67,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 36,
              gust_kph: 58,
              uv: 1,
            },
            {
              time_epoch: 1639119600,
              time: "2021-12-10 07:00",
              temp_c: 5.6,
              temp_f: 42.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 25.3,
              wind_kph: 40.7,
              wind_degree: 307,
              wind_dir: "NW",
              pressure_mb: 997,
              pressure_in: 29.44,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 23,
              feelslike_c: 0,
              feelslike_f: 32,
              windchill_c: 0,
              windchill_f: 32,
              heatindex_c: 5.6,
              heatindex_f: 42.1,
              dewpoint_c: 1.9,
              dewpoint_f: 35.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 34.9,
              gust_kph: 56.2,
              uv: 1,
            },
            {
              time_epoch: 1639123200,
              time: "2021-12-10 08:00",
              temp_c: 5.4,
              temp_f: 41.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 25.1,
              wind_kph: 40.3,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 998,
              pressure_in: 29.48,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 17,
              feelslike_c: -0.2,
              feelslike_f: 31.6,
              windchill_c: -0.2,
              windchill_f: 31.6,
              heatindex_c: 5.4,
              heatindex_f: 41.7,
              dewpoint_c: 1.7,
              dewpoint_f: 35.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 34.4,
              gust_kph: 55.4,
              uv: 3,
            },
            {
              time_epoch: 1639126800,
              time: "2021-12-10 09:00",
              temp_c: 5.5,
              temp_f: 41.9,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 24.8,
              wind_kph: 40,
              wind_degree: 309,
              wind_dir: "NW",
              pressure_mb: 999,
              pressure_in: 29.51,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 22,
              feelslike_c: 0,
              feelslike_f: 32,
              windchill_c: 0,
              windchill_f: 32,
              heatindex_c: 5.5,
              heatindex_f: 41.9,
              dewpoint_c: 1.7,
              dewpoint_f: 35.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 33.3,
              gust_kph: 53.6,
              uv: 3,
            },
            {
              time_epoch: 1639130400,
              time: "2021-12-10 10:00",
              temp_c: 5.8,
              temp_f: 42.4,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 24.4,
              wind_kph: 39.2,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1000,
              pressure_in: 29.53,
              precip_mm: 0,
              precip_in: 0,
              humidity: 76,
              cloud: 16,
              feelslike_c: 0.4,
              feelslike_f: 32.7,
              windchill_c: 0.4,
              windchill_f: 32.7,
              heatindex_c: 5.8,
              heatindex_f: 42.4,
              dewpoint_c: 1.8,
              dewpoint_f: 35.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 32,
              gust_kph: 51.5,
              uv: 3,
            },
            {
              time_epoch: 1639134000,
              time: "2021-12-10 11:00",
              temp_c: 7.2,
              temp_f: 45,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 23.9,
              wind_kph: 38.5,
              wind_degree: 309,
              wind_dir: "NW",
              pressure_mb: 1001,
              pressure_in: 29.55,
              precip_mm: 0,
              precip_in: 0,
              humidity: 73,
              cloud: 8,
              feelslike_c: 2.3,
              feelslike_f: 36.1,
              windchill_c: 2.3,
              windchill_f: 36.1,
              heatindex_c: 7.2,
              heatindex_f: 45,
              dewpoint_c: 2.7,
              dewpoint_f: 36.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 27.5,
              gust_kph: 44.3,
              uv: 3,
            },
            {
              time_epoch: 1639137600,
              time: "2021-12-10 12:00",
              temp_c: 7.3,
              temp_f: 45.1,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 24.6,
              wind_kph: 39.6,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1001,
              pressure_in: 29.57,
              precip_mm: 0,
              precip_in: 0,
              humidity: 72,
              cloud: 16,
              feelslike_c: 2.4,
              feelslike_f: 36.3,
              windchill_c: 2.4,
              windchill_f: 36.3,
              heatindex_c: 7.3,
              heatindex_f: 45.1,
              dewpoint_c: 2.6,
              dewpoint_f: 36.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 28.4,
              gust_kph: 45.7,
              uv: 3,
            },
            {
              time_epoch: 1639141200,
              time: "2021-12-10 13:00",
              temp_c: 7.5,
              temp_f: 45.5,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 24.4,
              wind_kph: 39.2,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1002,
              pressure_in: 29.59,
              precip_mm: 0,
              precip_in: 0,
              humidity: 71,
              cloud: 18,
              feelslike_c: 2.7,
              feelslike_f: 36.9,
              windchill_c: 2.7,
              windchill_f: 36.9,
              heatindex_c: 7.5,
              heatindex_f: 45.5,
              dewpoint_c: 2.6,
              dewpoint_f: 36.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 28,
              gust_kph: 45,
              uv: 3,
            },
            {
              time_epoch: 1639144800,
              time: "2021-12-10 14:00",
              temp_c: 7.6,
              temp_f: 45.7,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 24.6,
              wind_kph: 39.6,
              wind_degree: 307,
              wind_dir: "NW",
              pressure_mb: 1003,
              pressure_in: 29.61,
              precip_mm: 0,
              precip_in: 0,
              humidity: 70,
              cloud: 22,
              feelslike_c: 2.8,
              feelslike_f: 37,
              windchill_c: 2.8,
              windchill_f: 37,
              heatindex_c: 7.6,
              heatindex_f: 45.7,
              dewpoint_c: 2.6,
              dewpoint_f: 36.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 28.4,
              gust_kph: 45.7,
              uv: 3,
            },
            {
              time_epoch: 1639148400,
              time: "2021-12-10 15:00",
              temp_c: 7.9,
              temp_f: 46.2,
              is_day: 1,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000,
              },
              wind_mph: 23.9,
              wind_kph: 38.5,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1004,
              pressure_in: 29.64,
              precip_mm: 0,
              precip_in: 0,
              humidity: 70,
              cloud: 14,
              feelslike_c: 3.3,
              feelslike_f: 37.9,
              windchill_c: 3.3,
              windchill_f: 37.9,
              heatindex_c: 7.9,
              heatindex_f: 46.2,
              dewpoint_c: 2.8,
              dewpoint_f: 37,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 27.5,
              gust_kph: 44.3,
              uv: 3,
            },
            {
              time_epoch: 1639152000,
              time: "2021-12-10 16:00",
              temp_c: 8.4,
              temp_f: 47.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 23.3,
              wind_kph: 37.4,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1005,
              pressure_in: 29.67,
              precip_mm: 0,
              precip_in: 0,
              humidity: 72,
              cloud: 6,
              feelslike_c: 4,
              feelslike_f: 39.2,
              windchill_c: 4,
              windchill_f: 39.2,
              heatindex_c: 8.4,
              heatindex_f: 47.1,
              dewpoint_c: 3.6,
              dewpoint_f: 38.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 26.8,
              gust_kph: 43.2,
              uv: 1,
            },
            {
              time_epoch: 1639155600,
              time: "2021-12-10 17:00",
              temp_c: 8,
              temp_f: 46.4,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 22.1,
              wind_kph: 35.6,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1006,
              pressure_in: 29.7,
              precip_mm: 0,
              precip_in: 0,
              humidity: 73,
              cloud: 8,
              feelslike_c: 3.6,
              feelslike_f: 38.5,
              windchill_c: 3.6,
              windchill_f: 38.5,
              heatindex_c: 8,
              heatindex_f: 46.4,
              dewpoint_c: 3.5,
              dewpoint_f: 38.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 25.5,
              gust_kph: 41,
              uv: 1,
            },
            {
              time_epoch: 1639159200,
              time: "2021-12-10 18:00",
              temp_c: 8.3,
              temp_f: 46.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 21.3,
              wind_kph: 34.2,
              wind_degree: 311,
              wind_dir: "NW",
              pressure_mb: 1007,
              pressure_in: 29.73,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 5,
              feelslike_c: 4.1,
              feelslike_f: 39.4,
              windchill_c: 4.1,
              windchill_f: 39.4,
              heatindex_c: 8.3,
              heatindex_f: 46.9,
              dewpoint_c: 4,
              dewpoint_f: 39.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 24.4,
              gust_kph: 39.2,
              uv: 1,
            },
            {
              time_epoch: 1639162800,
              time: "2021-12-10 19:00",
              temp_c: 8.6,
              temp_f: 47.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 21,
              wind_kph: 33.8,
              wind_degree: 312,
              wind_dir: "NW",
              pressure_mb: 1008,
              pressure_in: 29.77,
              precip_mm: 0,
              precip_in: 0,
              humidity: 75,
              cloud: 4,
              feelslike_c: 4.5,
              feelslike_f: 40.1,
              windchill_c: 4.5,
              windchill_f: 40.1,
              heatindex_c: 8.6,
              heatindex_f: 47.5,
              dewpoint_c: 4.5,
              dewpoint_f: 40.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 24.2,
              gust_kph: 38.9,
              uv: 1,
            },
            {
              time_epoch: 1639166400,
              time: "2021-12-10 20:00",
              temp_c: 5.6,
              temp_f: 42.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 20.4,
              wind_kph: 32.8,
              wind_degree: 311,
              wind_dir: "NW",
              pressure_mb: 1009,
              pressure_in: 29.8,
              precip_mm: 0,
              precip_in: 0,
              humidity: 76,
              cloud: 3,
              feelslike_c: 0.6,
              feelslike_f: 33.1,
              windchill_c: 0.6,
              windchill_f: 33.1,
              heatindex_c: 5.6,
              heatindex_f: 42.1,
              dewpoint_c: 1.8,
              dewpoint_f: 35.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 27.7,
              gust_kph: 44.6,
              uv: 1,
            },
            {
              time_epoch: 1639170000,
              time: "2021-12-10 21:00",
              temp_c: 5.5,
              temp_f: 41.9,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 19.5,
              wind_kph: 31.3,
              wind_degree: 312,
              wind_dir: "NW",
              pressure_mb: 1010,
              pressure_in: 29.83,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 3,
              feelslike_c: 0.6,
              feelslike_f: 33.1,
              windchill_c: 0.6,
              windchill_f: 33.1,
              heatindex_c: 5.5,
              heatindex_f: 41.9,
              dewpoint_c: 1.8,
              dewpoint_f: 35.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 26.4,
              gust_kph: 42.5,
              uv: 1,
            },
            {
              time_epoch: 1639173600,
              time: "2021-12-10 22:00",
              temp_c: 5.4,
              temp_f: 41.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 18.6,
              wind_kph: 29.9,
              wind_degree: 312,
              wind_dir: "NW",
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 3,
              feelslike_c: 0.6,
              feelslike_f: 33.1,
              windchill_c: 0.6,
              windchill_f: 33.1,
              heatindex_c: 5.4,
              heatindex_f: 41.7,
              dewpoint_c: 1.7,
              dewpoint_f: 35.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 25.5,
              gust_kph: 41,
              uv: 1,
            },
            {
              time_epoch: 1639177200,
              time: "2021-12-10 23:00",
              temp_c: 5.4,
              temp_f: 41.7,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 17.7,
              wind_kph: 28.4,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1012,
              pressure_in: 29.88,
              precip_mm: 0,
              precip_in: 0,
              humidity: 78,
              cloud: 4,
              feelslike_c: 0.7,
              feelslike_f: 33.3,
              windchill_c: 0.7,
              windchill_f: 33.3,
              heatindex_c: 5.4,
              heatindex_f: 41.7,
              dewpoint_c: 1.9,
              dewpoint_f: 35.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23.9,
              gust_kph: 38.5,
              uv: 1,
            },
          ],
        },
        {
          date: "2021-12-11",
          date_epoch: 1639180800,
          day: {
            maxtemp_c: 9.8,
            maxtemp_f: 49.6,
            mintemp_c: 4.5,
            mintemp_f: 40.1,
            avgtemp_c: 7.3,
            avgtemp_f: 45.2,
            maxwind_mph: 19.9,
            maxwind_kph: 32,
            totalprecip_mm: 2.4,
            totalprecip_in: 0.09,
            avgvis_km: 9,
            avgvis_miles: 5,
            avghumidity: 82,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 77,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 1,
          },
          astro: {
            sunrise: "07:53 AM",
            sunset: "03:55 PM",
            moonrise: "01:01 PM",
            moonset: "No moonset",
            moon_phase: "Waxing Gibbous",
            moon_illumination: "55",
          },
          hour: [
            {
              time_epoch: 1639180800,
              time: "2021-12-11 00:00",
              temp_c: 5,
              temp_f: 41,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 15.9,
              wind_kph: 25.6,
              wind_degree: 308,
              wind_dir: "NW",
              pressure_mb: 1013,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              humidity: 79,
              cloud: 5,
              feelslike_c: 0.5,
              feelslike_f: 32.9,
              windchill_c: 0.5,
              windchill_f: 32.9,
              heatindex_c: 5,
              heatindex_f: 41,
              dewpoint_c: 1.7,
              dewpoint_f: 35.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 23.3,
              gust_kph: 37.4,
              uv: 1,
            },
            {
              time_epoch: 1639184400,
              time: "2021-12-11 01:00",
              temp_c: 4.8,
              temp_f: 40.6,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 14.1,
              wind_kph: 22.7,
              wind_degree: 311,
              wind_dir: "NW",
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              humidity: 80,
              cloud: 6,
              feelslike_c: 0.5,
              feelslike_f: 32.9,
              windchill_c: 0.5,
              windchill_f: 32.9,
              heatindex_c: 4.8,
              heatindex_f: 40.6,
              dewpoint_c: 1.7,
              dewpoint_f: 35.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 21.5,
              gust_kph: 34.6,
              uv: 1,
            },
            {
              time_epoch: 1639188000,
              time: "2021-12-11 02:00",
              temp_c: 4.7,
              temp_f: 40.5,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 12.1,
              wind_kph: 19.4,
              wind_degree: 312,
              wind_dir: "NW",
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0,
              precip_in: 0,
              humidity: 81,
              cloud: 6,
              feelslike_c: 0.8,
              feelslike_f: 33.4,
              windchill_c: 0.8,
              windchill_f: 33.4,
              heatindex_c: 4.7,
              heatindex_f: 40.5,
              dewpoint_c: 1.8,
              dewpoint_f: 35.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.6,
              gust_kph: 29.9,
              uv: 1,
            },
            {
              time_epoch: 1639191600,
              time: "2021-12-11 03:00",
              temp_c: 4.5,
              temp_f: 40.1,
              is_day: 0,
              condition: {
                text: "Clear",
                icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                code: 1000,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 311,
              wind_dir: "NW",
              pressure_mb: 1015,
              pressure_in: 29.97,
              precip_mm: 0,
              precip_in: 0,
              humidity: 82,
              cloud: 10,
              feelslike_c: 0.8,
              feelslike_f: 33.4,
              windchill_c: 0.8,
              windchill_f: 33.4,
              heatindex_c: 4.5,
              heatindex_f: 40.1,
              dewpoint_c: 1.7,
              dewpoint_f: 35.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.2,
              gust_kph: 27.7,
              uv: 1,
            },
            {
              time_epoch: 1639195200,
              time: "2021-12-11 04:00",
              temp_c: 4.5,
              temp_f: 40.1,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 312,
              wind_dir: "NW",
              pressure_mb: 1016,
              pressure_in: 29.99,
              precip_mm: 0,
              precip_in: 0,
              humidity: 81,
              cloud: 37,
              feelslike_c: 1.1,
              feelslike_f: 34,
              windchill_c: 1.1,
              windchill_f: 34,
              heatindex_c: 4.5,
              heatindex_f: 40.1,
              dewpoint_c: 1.6,
              dewpoint_f: 34.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.4,
              gust_kph: 24.8,
              uv: 1,
            },
            {
              time_epoch: 1639198800,
              time: "2021-12-11 05:00",
              temp_c: 4.5,
              temp_f: 40.1,
              is_day: 0,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 310,
              wind_dir: "NW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              humidity: 81,
              cloud: 57,
              feelslike_c: 1.2,
              feelslike_f: 34.2,
              windchill_c: 1.2,
              windchill_f: 34.2,
              heatindex_c: 4.5,
              heatindex_f: 40.1,
              dewpoint_c: 1.5,
              dewpoint_f: 34.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.5,
              gust_kph: 23.4,
              uv: 1,
            },
            {
              time_epoch: 1639202400,
              time: "2021-12-11 06:00",
              temp_c: 4.6,
              temp_f: 40.3,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 7.8,
              wind_kph: 12.6,
              wind_degree: 303,
              wind_dir: "WNW",
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              humidity: 80,
              cloud: 71,
              feelslike_c: 1.7,
              feelslike_f: 35.1,
              windchill_c: 1.7,
              windchill_f: 35.1,
              heatindex_c: 4.6,
              heatindex_f: 40.3,
              dewpoint_c: 1.5,
              dewpoint_f: 34.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.8,
              gust_kph: 20.5,
              uv: 1,
            },
            {
              time_epoch: 1639206000,
              time: "2021-12-11 07:00",
              temp_c: 4.8,
              temp_f: 40.6,
              is_day: 0,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 6.7,
              wind_kph: 10.8,
              wind_degree: 298,
              wind_dir: "WNW",
              pressure_mb: 1018,
              pressure_in: 30.05,
              precip_mm: 0,
              precip_in: 0,
              humidity: 79,
              cloud: 87,
              feelslike_c: 2.2,
              feelslike_f: 36,
              windchill_c: 2.2,
              windchill_f: 36,
              heatindex_c: 4.8,
              heatindex_f: 40.6,
              dewpoint_c: 1.5,
              dewpoint_f: 34.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11,
              gust_kph: 17.6,
              uv: 1,
            },
            {
              time_epoch: 1639209600,
              time: "2021-12-11 08:00",
              temp_c: 5,
              temp_f: 41,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 289,
              wind_dir: "WNW",
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0,
              precip_in: 0,
              humidity: 79,
              cloud: 100,
              feelslike_c: 2.7,
              feelslike_f: 36.9,
              windchill_c: 2.7,
              windchill_f: 36.9,
              heatindex_c: 5,
              heatindex_f: 41,
              dewpoint_c: 1.6,
              dewpoint_f: 34.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.8,
              gust_kph: 15.8,
              uv: 2,
            },
            {
              time_epoch: 1639213200,
              time: "2021-12-11 09:00",
              temp_c: 5.4,
              temp_f: 41.7,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 5.8,
              wind_kph: 9.4,
              wind_degree: 279,
              wind_dir: "W",
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0,
              precip_in: 0,
              humidity: 78,
              cloud: 45,
              feelslike_c: 3.3,
              feelslike_f: 37.9,
              windchill_c: 3.3,
              windchill_f: 37.9,
              heatindex_c: 5.4,
              heatindex_f: 41.7,
              dewpoint_c: 1.9,
              dewpoint_f: 35.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.2,
              gust_kph: 14.8,
              uv: 3,
            },
            {
              time_epoch: 1639216800,
              time: "2021-12-11 10:00",
              temp_c: 6.1,
              temp_f: 43,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 6.3,
              wind_kph: 10.1,
              wind_degree: 268,
              wind_dir: "W",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 77,
              cloud: 43,
              feelslike_c: 4,
              feelslike_f: 39.2,
              windchill_c: 4,
              windchill_f: 39.2,
              heatindex_c: 6.1,
              heatindex_f: 43,
              dewpoint_c: 2.4,
              dewpoint_f: 36.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.4,
              gust_kph: 15.1,
              uv: 3,
            },
            {
              time_epoch: 1639220400,
              time: "2021-12-11 11:00",
              temp_c: 7,
              temp_f: 44.6,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 258,
              wind_dir: "WSW",
              pressure_mb: 1020,
              pressure_in: 30.11,
              precip_mm: 0,
              precip_in: 0,
              humidity: 75,
              cloud: 32,
              feelslike_c: 4.6,
              feelslike_f: 40.3,
              windchill_c: 4.6,
              windchill_f: 40.3,
              heatindex_c: 7,
              heatindex_f: 44.6,
              dewpoint_c: 3,
              dewpoint_f: 37.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 3,
            },
            {
              time_epoch: 1639224000,
              time: "2021-12-11 12:00",
              temp_c: 7.6,
              temp_f: 45.7,
              is_day: 1,
              condition: {
                text: "Partly cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                code: 1003,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 251,
              wind_dir: "WSW",
              pressure_mb: 1020,
              pressure_in: 30.11,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 45,
              feelslike_c: 4.9,
              feelslike_f: 40.8,
              windchill_c: 4.9,
              windchill_f: 40.8,
              heatindex_c: 7.6,
              heatindex_f: 45.7,
              dewpoint_c: 3.2,
              dewpoint_f: 37.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13,
              gust_kph: 20.9,
              uv: 3,
            },
            {
              time_epoch: 1639227600,
              time: "2021-12-11 13:00",
              temp_c: 8.6,
              temp_f: 47.5,
              is_day: 1,
              condition: {
                text: "Cloudy",
                icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                code: 1006,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 246,
              wind_dir: "WSW",
              pressure_mb: 1020,
              pressure_in: 30.11,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 78,
              feelslike_c: 6.1,
              feelslike_f: 43,
              windchill_c: 6.1,
              windchill_f: 43,
              heatindex_c: 8.6,
              heatindex_f: 47.5,
              dewpoint_c: 4.1,
              dewpoint_f: 39.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.5,
              gust_kph: 20.2,
              uv: 2,
            },
            {
              time_epoch: 1639231200,
              time: "2021-12-11 14:00",
              temp_c: 9.1,
              temp_f: 48.4,
              is_day: 1,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 241,
              wind_dir: "WSW",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 74,
              cloud: 100,
              feelslike_c: 6.5,
              feelslike_f: 43.7,
              windchill_c: 6.5,
              windchill_f: 43.7,
              heatindex_c: 9.1,
              heatindex_f: 48.4,
              dewpoint_c: 4.8,
              dewpoint_f: 40.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.3,
              gust_kph: 23,
              uv: 2,
            },
            {
              time_epoch: 1639234800,
              time: "2021-12-11 15:00",
              temp_c: 9,
              temp_f: 48.2,
              is_day: 1,
              condition: {
                text: "Patchy rain possible",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 244,
              wind_dir: "WSW",
              pressure_mb: 1020,
              pressure_in: 30.11,
              precip_mm: 0.1,
              precip_in: 0,
              humidity: 78,
              cloud: 100,
              feelslike_c: 6.1,
              feelslike_f: 43,
              windchill_c: 6.1,
              windchill_f: 43,
              heatindex_c: 9,
              heatindex_f: 48.2,
              dewpoint_c: 5.3,
              dewpoint_f: 41.5,
              will_it_rain: 0,
              chance_of_rain: 60,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.2,
              gust_kph: 27.7,
              uv: 2,
            },
            {
              time_epoch: 1639238400,
              time: "2021-12-11 16:00",
              temp_c: 8.9,
              temp_f: 48,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 231,
              wind_dir: "SW",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0,
              precip_in: 0,
              humidity: 83,
              cloud: 100,
              feelslike_c: 6.3,
              feelslike_f: 43.3,
              windchill_c: 6.3,
              windchill_f: 43.3,
              heatindex_c: 8.9,
              heatindex_f: 48,
              dewpoint_c: 6.2,
              dewpoint_f: 43.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.8,
              gust_kph: 23.8,
              uv: 1,
            },
            {
              time_epoch: 1639242000,
              time: "2021-12-11 17:00",
              temp_c: 9.2,
              temp_f: 48.6,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 11.6,
              wind_kph: 18.7,
              wind_degree: 212,
              wind_dir: "SSW",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0.2,
              precip_in: 0.01,
              humidity: 86,
              cloud: 100,
              feelslike_c: 6.5,
              feelslike_f: 43.7,
              windchill_c: 6.5,
              windchill_f: 43.7,
              heatindex_c: 9.2,
              heatindex_f: 48.6,
              dewpoint_c: 6.9,
              dewpoint_f: 44.4,
              will_it_rain: 1,
              chance_of_rain: 72,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 1,
            },
            {
              time_epoch: 1639245600,
              time: "2021-12-11 18:00",
              temp_c: 9.8,
              temp_f: 49.6,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 14.5,
              wind_kph: 23.4,
              wind_degree: 206,
              wind_dir: "SSW",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0,
              precip_in: 0,
              humidity: 86,
              cloud: 100,
              feelslike_c: 6.8,
              feelslike_f: 44.2,
              windchill_c: 6.8,
              windchill_f: 44.2,
              heatindex_c: 9.8,
              heatindex_f: 49.6,
              dewpoint_c: 7.6,
              dewpoint_f: 45.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.5,
              gust_kph: 31.3,
              uv: 1,
            },
            {
              time_epoch: 1639249200,
              time: "2021-12-11 19:00",
              temp_c: 10.2,
              temp_f: 50.4,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 17,
              wind_kph: 27.4,
              wind_degree: 204,
              wind_dir: "SSW",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0.3,
              precip_in: 0.01,
              humidity: 89,
              cloud: 100,
              feelslike_c: 7,
              feelslike_f: 44.6,
              windchill_c: 7,
              windchill_f: 44.6,
              heatindex_c: 10.2,
              heatindex_f: 50.4,
              dewpoint_c: 8.5,
              dewpoint_f: 47.3,
              will_it_rain: 1,
              chance_of_rain: 77,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 22.1,
              gust_kph: 35.6,
              uv: 1,
            },
            {
              time_epoch: 1639252800,
              time: "2021-12-11 20:00",
              temp_c: 10.2,
              temp_f: 50.4,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 18.8,
              wind_kph: 30.2,
              wind_degree: 210,
              wind_dir: "SSW",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0,
              precip_in: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 6.8,
              feelslike_f: 44.2,
              windchill_c: 6.8,
              windchill_f: 44.2,
              heatindex_c: 10.2,
              heatindex_f: 50.4,
              dewpoint_c: 9,
              dewpoint_f: 48.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 26.8,
              gust_kph: 43.2,
              uv: 1,
            },
            {
              time_epoch: 1639256400,
              time: "2021-12-11 21:00",
              temp_c: 10.5,
              temp_f: 50.9,
              is_day: 0,
              condition: {
                text: "Light rain",
                icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
                code: 1183,
              },
              wind_mph: 19.7,
              wind_kph: 31.7,
              wind_degree: 210,
              wind_dir: "SSW",
              pressure_mb: 1020,
              pressure_in: 30.11,
              precip_mm: 1.3,
              precip_in: 0.05,
              humidity: 94,
              cloud: 100,
              feelslike_c: 7.1,
              feelslike_f: 44.8,
              windchill_c: 7.1,
              windchill_f: 44.8,
              heatindex_c: 10.5,
              heatindex_f: 50.9,
              dewpoint_c: 9.6,
              dewpoint_f: 49.3,
              will_it_rain: 1,
              chance_of_rain: 76,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 27.7,
              gust_kph: 44.6,
              uv: 1,
            },
            {
              time_epoch: 1639260000,
              time: "2021-12-11 22:00",
              temp_c: 10.7,
              temp_f: 51.3,
              is_day: 0,
              condition: {
                text: "Overcast",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 19.9,
              wind_kph: 32,
              wind_degree: 211,
              wind_dir: "SSW",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              humidity: 95,
              cloud: 100,
              feelslike_c: 7.4,
              feelslike_f: 45.3,
              windchill_c: 7.4,
              windchill_f: 45.3,
              heatindex_c: 10.7,
              heatindex_f: 51.3,
              dewpoint_c: 10,
              dewpoint_f: 50,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 28.2,
              gust_kph: 45.4,
              uv: 1,
            },
            {
              time_epoch: 1639263600,
              time: "2021-12-11 23:00",
              temp_c: 11.1,
              temp_f: 52,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 19.9,
              wind_kph: 32,
              wind_degree: 222,
              wind_dir: "SW",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0.5,
              precip_in: 0.02,
              humidity: 97,
              cloud: 100,
              feelslike_c: 7.9,
              feelslike_f: 46.2,
              windchill_c: 7.9,
              windchill_f: 46.2,
              heatindex_c: 11.1,
              heatindex_f: 52,
              dewpoint_c: 10.6,
              dewpoint_f: 51.1,
              will_it_rain: 1,
              chance_of_rain: 75,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 28.9,
              gust_kph: 46.4,
              uv: 1,
            },
          ],
        },
      ],
    },
    alerts: {
      alert: [],
    },
  });

  // Set UseEffect to update every 1000ms (1s)
  useEffect(() => {
    setInterval(() => setDateState(new Date()), 1000);
    const getWeatherFromApi = async () => {
      const response = await fetch(
        "http://api.weatherapi.com/v1/forecast.json?key=ac517e0edf3142a6ae282635211410&q=Brighton&days=3&aqi=no&alerts=yes"
      );
      const responseJson = await response.json();
      console.log("json", responseJson);
      setWeatherState(responseJson);
    };
    getWeatherFromApi();
  }, []);

  return (
    <div className="h-full w-full flex justify-between">
      <div className="px-4 py-5">
        <span className="block text-7xl font-semibold">
          {currentDate.toLocaleString("en-US", {
            hour: "numeric",
            minute: "numeric",
            hour12: true,
          })}
        </span>
        <span className="text-4xl">
          {currentDate.toLocaleDateString("en-GB", {
            dateStyle: "full",
          })}
        </span>
      </div>
      <div className="px-4 py-5  ">
        <span className="block text-5xl font-semibold">
          {currentWeather.current.temp_c}°C
        </span>
        <span className="text-2xl ">
          <img src={currentWeather.current.condition.icon} alt="" />
          {currentWeather.location.name} -{" "}
          {currentWeather.current.condition.text}
        </span>
      </div>
      <div className="px-4 py-5  ">
        <span className="block text-5xl font-semibold">
          {currentWeather.forecast.forecastday[1].day.avgtemp_c}°C
        </span>
        <span className="text-2xl ">
          <img
            src={currentWeather.forecast.forecastday[1].day.condition.icon}
            alt="icon"
          />
          {currentWeather.location.name} -{" "}
          {currentWeather.forecast.forecastday[1].day.condition.text}
        </span>
      </div>
      <div className="px-4 py-5  ">
        <span className="block text-5xl font-semibold">
          {currentWeather.forecast.forecastday[2].day.avgtemp_c}°C
        </span>
        <span className="text-2xl ">
          <img
            src={currentWeather.forecast.forecastday[2].day.condition.icon}
            alt="icon"
          />
          {currentWeather.location.name} -{" "}
          {currentWeather.forecast.forecastday[2].day.condition.text}
         
        </span>
       
      </div>
      
    </div>
  );
}
